name: Push Images

on:
  pull_request:
    branches: [ main, test/build-push-ci ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Push Updated Images
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0
    
    - name: Login to Quay.io
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Push Changed Images
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        BASE_DIR=$(pwd)

        for file in ${ALL_CHANGED_FILES}; do
            dir="$(dirname "${file}")"
            echo "Change detected in $dir ..."
            cd $dir
            if [ ! -f config.env ]; then
                echo "No config.env file present in changed directory, skipping push ..."
                continue
            fi
            source config.env
            echo "Running 'docker build' in $dir ..."
            if [ -f "Containerfile" ]; then
                docker build -t "${IMAGE_NAME}":"${IMAGE_TAG}" -f Containerfile .
            else
                docker build -t "${IMAGE_NAME}":"${IMAGE_TAG}" -f Dockerfile .
            fi
            docker push "${IMAGE_NAME}":"${IMAGE_TAG}"
            cd $BASE_DIR
        done

   